apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.test1.name }}
spec:
  replicas: {{ .Values.test1.scale }}
  template:
    metadata:
      labels:
        app: {{ .Values.test1.name }}
    spec:
      containers:
      - name: {{ .Values.test1.name }}
        image: nginx:{{ .Values.test1.tag }}
        ports:
        - containerPort: 80
