apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.test2 }}
spec:
  replicas: {{ .Values.test2.scale }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.test2.tag }}
        ports:
        - containerPort: 80
